import { Product } from "@/types";


export const products: Product[] = [
  {
    id: "1",
    name: "Floral Summer Dress",
    price: 12500,
    category: "clothing",
    description: "A beautiful floral dress perfect for summer outings and casual events.",
    image: "/products/dress1.jpg",
    emoji: "👗",
    rating: 4.5,
    reviews: 24,
    stock: 15,
    featured: true,
  },
  {
    id: "2",
    name: "Men's Casual Polo",
    price: 7500,
    category: "clothing",
    description: "Comfortable everyday polo shirt available in multiple colors.",
    image: "/products/men1.jpg",
    emoji: "👕",
    rating: 4.2,
    reviews: 31,
    stock: 40,
    featured: true,
  },
  {
    id: "3",
    name: "Women's Ankara Skirt",
    price: 9500,
    category: "clothing",
    description: "Vibrant Ankara print skirt, handcrafted with quality fabric.",
    image: "/products/skirt1.jpg",
    emoji: "🧣",
    rating: 4.6,
    reviews: 19,
    stock: 20,
  },
  {
    id: "4",
    name: "Standing Blender",
    price: 35000,
    category: "appliances",
    description: "High-powered blender for smoothies, soups and more.",
    image: "/products/blend2.jpg",
    emoji: "🥤",
    rating: 4.8,
    reviews: 56,
    stock: 10,
    featured: true,
  },
  {
    id: "5",
    name: "Air Fryer 5L",
    price: 65000,
    category: "appliances",
    description: "Fry, bake and grill with little to no oil. Healthy cooking made easy.",
    image: "/products/air2.jpg",
    emoji: "🍟",
    rating: 4.7,
    reviews: 89,
    stock: 8,
    featured: true,
  },
  {
    id: "6",
    name: "Electric Iron",
    price: 12000,
    category: "appliances",
    description: "Steam iron with auto shut-off for safe and smooth ironing.",
    image: "/products/iron2.jpg",
    emoji: "🔌",
    rating: 4.3,
    reviews: 44,
    stock: 25,
  },
  {
    id: "7",
    name: "Non-stick Frying Pan",
    price: 8500,
    category: "kitchen",
    description: "Premium non-stick pan that makes cooking and cleaning effortless.",
    image: "/products/pan1.jpg",
    emoji: "🍳",
    rating: 4.3,
    reviews: 18,
    stock: 30,
    featured: true,
  },
  {
    id: "8",
    name: "Wooden Cutting Board",
    price: 4500,
    category: "kitchen",
    description: "Durable hardwood cutting board, gentle on knives.",
    image: "/products/cut1.jpg",
    emoji: "🪵",
    rating: 4.1,
    reviews: 12,
    stock: 50,
  },
  {
    id: "9",
    name: "Knife Set (6 piece)",
    price: 18000,
    category: "kitchen",
    description: "Professional grade stainless steel knife set with wooden block.",
    image: "/products/kk2.jpg",
    emoji: "🔪",
    rating: 4.6,
    reviews: 37,
    stock: 15,
  },
  {
    id: "10",
    name: "Glow Serum Set",
    price: 15000,
    category: "cosmetics",
    description: "Brightening serum with Vitamin C and hyaluronic acid for glowing skin.",
    image: "/products/glow1.jpg",
    emoji: "✨",
    rating: 4.9,
    reviews: 102,
    stock: 60,
    featured: true,
  },
  {
    id: "11",
    name: "Matte Lipstick Collection",
    price: 6500,
    category: "cosmetics",
    description: "Long-lasting matte lipstick set in 6 gorgeous shades.",
    image: "/products/lip1.jpg",
    emoji: "💄",
    rating: 4.7,
    reviews: 78,
    stock: 45,
  },
  {
    id: "12",
    name: "Sunscreen SPF 50",
    price: 5500,
    category: "cosmetics",
    description: "Lightweight daily sunscreen that protects and moisturizes.",
    image: "/products/ss1.jpg",
    emoji: "🧴",
    rating: 4.5,
    reviews: 63,
    stock: 35,
  },
];